### PR TITLE
Add ChainSafe js-libp2p maintainers as members

### PR DESCRIPTION
**Pull request by wemeetagain**
@mpetrunic and I are helping maintain js-libp2p and there is overlap between the libraries under the libp2p org and this one.
We'd like to be able to give code reviews and help maintain the js libraries here.

We don't need any special permissions, so I didn't go thru the trouble of adding a special team as was done here:
https://github.com/libp2p/github-mgmt/pull/7

cc @biglep

### CODE REVIEW

**Review by BigLep — APPROVED** [review]

**Comment by wemeetagain** [comment]
Thanks @galargh

**Comment by wemeetagain** [comment]
@galargh can you deploy this change?

**Comment by galargh** [comment]
> @galargh can you deploy this change?

It was automatically deployed immediately after the merge. I can see in the settings that you have a pending invitation.

**Comment by wemeetagain** [comment]
Ah thanks, the email got lost in the clutter!

**Pull request merged**
